43

diff --git a/test1/Jenkinsfile b/test1/Jenkinsfile
--- a/test1/Jenkinsfile
+++ b/test1/Jenkinsfile
@@ -9,33 +9,39 @@ pipeline {
         }
         stage('Setup Build Tool') {
             steps {
-                sh '''
-                if ! command -v mvn &> /dev/null; then
-                    echo "Maven not found! Downloading Maven 3.9.5..."
-                    curl -sL -o apache-maven-3.9.5-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
-                    tar -xzf apache-maven-3.9.5-bin.tar.gz
-                fi
-                '''
+                dir('test1') {
+                    sh '''
+                    if ! command -v mvn &> /dev/null; then
+                        echo "Maven not found! Downloading Maven 3.9.5..."
+                        curl -sL -o apache-maven-3.9.5-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
+                        tar -xzf apache-maven-3.9.5-bin.tar.gz
+                    fi
+                    '''
+                }
             }
         }
         stage('Build') {
             steps {
                 echo 'Building the project...'
-                sh '''
-                export MAVEN_HOME="$(pwd)/apache-maven-3.9.5"
-                export PATH="$MAVEN_HOME/bin:$PATH"
-                mvn clean compile
-                '''
+                dir('test1') {
+                    sh '''
+                    export MAVEN_HOME="$(pwd)/apache-maven-3.9.5"
+                    export PATH="$MAVEN_HOME/bin:$PATH"
+                    mvn clean compile
+                    '''
+                }
             }
         }
         stage('Test') {
             steps {
                 echo 'Testing...'
-                sh '''
-                export MAVEN_HOME="$(pwd)/apache-maven-3.9.5"
-                export PATH="$MAVEN_HOME/bin:$PATH"
-                mvn test
-                '''
+                dir('test1') {
+                    sh '''
+                    export MAVEN_HOME="$(pwd)/apache-maven-3.9.5"
+                    export PATH="$MAVEN_HOME/bin:$PATH"
+                    mvn test
+                    '''
+                }
             }
         }
     }
